ember-redux/ember-redux

README.md
blueprints/.jshintrc
blueprints/ember-redux/index.js
package.json

This enables a one-line install of ember-redux
TEST WITH:
```
ember install "ember-redux@dustinfarris/ember-redux#c2d0055"
```
CHANGES:
- Create default blueprint which adds dependencies to user's own package.json
- Move internal dependencies to devDependencies

Create default blueprint

---

addon/route.js
tests/acceptance/route-hooks-test.js
tests/dummy/app/components/item-list/component.js
tests/dummy/app/items/route.js
tests/dummy/app/reducers/index.js
tests/dummy/app/reducers/models.js

Reference
===
https://github.com/toranb/ember-redux/issues/17#issuecomment-240909216
Changes
===
* properly exploded input arguments and now using apply to call them in `addon/route.js`
* added an acceptance-test for route-hooks
* modified the item-list component and items route to accomodate for the afterModel test
* added a reducer to handle `AFTER_MODEL`
Unrelated Note
===
I was looking at the `addon/components/connect.js:41` when I came across this:
```javascript
this.unsubscribe = redux.subscribe(() => {
props.forEach(function(name) {
component.notifyPropertyChange(name);
});
});
``` 
And it looks like each time an action is sent to redux, we tell ember that the property changed even if the property didn't actually change... is this ok? I mean, granted I'm making a lot of assumptions …

17 - fixed arguments like transition not being passed into the route hook

---

addon/-private/equal.js
addon/components/connect.js
tests/acceptance/rerender-test.js
tests/dummy/app/components/filter-list/component.js
tests/dummy/app/components/list-html/component.js
tests/dummy/app/components/list-one/component.js
tests/dummy/app/components/list-two/component.js
tests/dummy/app/components/random-change/component.js
tests/dummy/app/components/random-one/component.js
tests/dummy/app/components/refresh-list/component.js
tests/dummy/app/components/unrelated-change/component.js
tests/dummy/app/components/unrelated-one/component.js
tests/dummy/app/lists/route.js
tests/dummy/app/lists/template.hbs
tests/dummy/app/reducers/index.js
tests/dummy/app/reducers/list.js
tests/dummy/app/router.js
tests/dummy/app/utilities/filter.js
tests/unit/-private/equal-test.js

This pull request aims to solve the performance problem that exists today with subscribe. Currently on any change we ask each component to re-render everything (not ideal) so in this PR we only ask for a re-render when state watched locally is truly different.

Only re-render when truly required

---

.editorconfig
.jshintrc
.travis.yml
bower.json
config/ember-try.js
package.json
tests/.jshintrc
tests/dummy/app/index.html
tests/dummy/app/router.js
tests/dummy/config/environment.js
tests/helpers/module-for-acceptance.js
tests/index.html

It was time to upgrade the project from ember-cli 2.4.2 => 2.8.0
Also I noticed we ran nearly every 2x build of ember and I don't think we truly need this anymore. Now we just run 2.0/each LTS and the beta with travis-ci

ember-cli upgrade

---

addon/components/connect.js
tests/integration/connect-test.js

So that the base component can use the `willDestroy` hook too.

Call super in component willDestroy.

---

addon/components/connect.js
tests/acceptance/rerender-test.js

If the redux state is changed by an outsider, acceptance tests can potentially fail as rerender occurs after the test completes.
Wrapping updateProps with Ember.run fixes this.

[BUG]: wrap updateProps in Ember.run

---

.gitignore
bower.json
package.json
tests/dummy/app/utilities/array.js
tests/dummy/config/environment.js
tests/index.html

Keeping up with the cool kids - the only huge jump I see is from `ember-cli-qunit v2.1.0 => v3`
This time it's just the bower/package.json/ember-cli updates :)

Update both ember and ember-cli to v2.9.1 

---

addon/components/connect.js
tests/acceptance/rerender-test.js

I've updated the rerender test to track each notifyPropertyChange more accurately. This should allow us to better evaluate the setProperties PR that Dustin has started on.
@dustinfarris you mind rebasing this after we merge it to see how the setProperties work compares?
@brettburley the only question I have before we land this - in the test I lookup the list-one component but since 2 instances are created ... how can I identify each independently so it's more clear in the test?

[TESTS]: updated rerender test to track notify via observer

---

addon/components/connect.js

This is a different approach to the concerns raised in #30
This greatly simplifies the code and transfers optimization responsibility to Ember, where it should stay if at all possible.
The properties work like this:
On init (and after every state change via redux.subscribe), the user props are computed using the user-supplied `mapStateToComputed` function.  The resulting object might look like e.g.:
```js
// props
{
users: [ { id: 1, name: 'Bob' } ]
}
```
The resulting props object is set on a private `_props` property on the component via `setProperties`, e.g.:
```js
this.get('_props').setProperties(props);
```
"read-only" aliases are set up to match what the user expects
```js
// Simplified
Ember.defineProperty(this, 'user', Ember.computed.readOnly('_props.user'));
```
This allows us to …

Use Ember.Object.setProperties to update props

---

addon/components/connect.js

I've simplified the callback workload to reduce the number of times we invoke redux.getState() in handleChange from 2x to 1x and also I've eliminated an unnecessary function (used previously in the shallowEqual days of connect). My hope is that we can achieve the same goal #41 set out to solve but without the tradeoff of holding state local in the component (and further -helping us avoid Ember.set / setProperties).
After the over notify problem was solved, the remaining "Problem Statement" back in #30 was that we call redux.getState() multiple times during re-render work and that could be expensive. This PR should solve a good chunk of that and I'm asking @dbashford to confirm we didn't break his app. In addition, I'm reaching out to @justinpark to confirm he won't run into a performance …

[PERFORMANCE]: avoid multiple redux.getState() calls in connect

---

app/services/redux.js

The way things look today it's very possible Ember.K will be deprecated
https://github.com/cibernox/rfcs/blob/738bd4c646ed679693ef733f99e1a10ab93242af/text/0000-deprecate-ember-k.md
This simply helps us be proactive instead of reactive - also the more vanillaJS the better :)

[REFACTOR]: remove Ember.K in favor of () => {}

---

.jshintrc
addon/components/connect.js

This replaces #47 
No functional changes, just syntax sugar and move `finalMapToComputed`/`finalDispatchToActions` to default args.

ES6ify connect

---

README.md
addon/components/connect.js
tests/dummy/app/components/count-list/component.js
tests/integration/connect-test.js

This adds a second argument to `stateToComputed` that contains an object with the attrs that were passed to a component.
E.g.:
```hbs
{{my-component userId=userId}}
```
```js
stateToComputed = (state, attrs) => {
return { user: getUserById(state, attrs.userId) };
}
```
This is analogous to [the same API in react-redux](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options).
As suggested by @wooandoo in #54, rather than pass `this.attrs` and leave it at that, a new object is computed that alleviates the need to crawl through the intermediary attr.  This object is cached for performance and only updated if the inbound attrs change as signaled by `didUpdateAttrs`.  More details can be found in the included docstring for …

[FEATURE] pass attrs to stateToComputed

---

addon/components/connect.js
tests/integration/connect-test.js

This restores the ability to pass `null` for `stateToComputed` when connecting a component.

Allow `null` stateToComputed argument

---

.gitignore
addon/components/connect.js
tests/integration/runloop-test.js

This fixes #64 
Starting with `2.10`, we've begun having issues with excessive and spammy `run` usage (and not just with ember-redux).
The `run(() => this.handleChange())` in particular was causing us problems.  In a relatively small app with 7-10 components getting 4 or 5 quick state updates in succession, we were hitting that `run` 50+ times in a short period of time. With `2.10` that consistently gave us an [`infinite rendering invalidation detected`](https://github.com/emberjs/ember.js/blob/855363285dc66ece8eac9f417375bd4d69460e7e/packages/ember-glimmer/lib/renderer.js#L156) error.
There isn't a lot of information about that particular error, and the Ember code is a bit obtuse, but based on a lot of experimentation the past few days it seems closely related to excessive run loop …

Reduce the number of run loops created when state changes

---

addon/components/connect.js
tests/acceptance/rerender-test.js
tests/dummy/app/components/count-list/component.js
tests/dummy/app/components/list-one/component.js
tests/dummy/app/lists/template.hbs
tests/dummy/app/reducers/list.js
tests/dummy/app/services/fake.js
tests/integration/connect-test.js

@foxnewsnetwork was asking for a 3rd argument for `stateToComputed` that would allow the user to pull from non attrs.
This example shows how I can pull a value from an injected service w/ the api change mentioned.
The next PR that follows this should likely add attrs/ and the instance arguments to `dispatchToActions` (as react-redux supports `ownProps` and it would be consistent with `stateToComputed`)

[FEATURE]: the component instance is now available as `this` for non [phat]Arrow

---

docs/configure.md
docs/cookbook.md
docs/ddau.md
docs/index.md
docs/quickstart.md

This escapes handlebars curly braces for Jekyll.
Fixes #83 
--patching into the beta/2x branch to keep it in sync with master

fix(docs): wrap docs in {% raw %} tags

---

package.json

Upgrade redux thunk and prepare the 2.0.0-beta.6 release (using beta/2x branch this time)

[DEPENDENCY]: upgraded redux/thunk shims in package.json

---

README.md

- Use nested header levels for clarity in Examples section
- Use a list, rather than a code block, for time travel debugging instructions
- Add a link to the redux dev tools

Improve Markdown structure and content in README

---

tests/integration/connect-test.js

This fixes the issue mentioned in the [ember v2.11.3 release](https://github.com/emberjs/ember.js/pull/14898)
This should also help unblock @sandersky and other PRs waiting for a solid build :)

[TESTS]: fixed readOnly assertion for ember 2.11.3

---

addon/components/connect.js
tests/acceptance/async-dispatch-test.js
tests/dummy/app/actions/index.js
tests/dummy/app/actionz/template.hbs
tests/dummy/app/components/less-boilerplate/component.js
tests/dummy/app/reducers/low.js
tests/dummy/app/router.js
tests/dummy/app/templates/application.hbs
tests/helpers/patch-middleware.js
tests/integration/connect-test.js
tests/zlast/zmiddleware-test.js

I took the work @jkarsrud started and extended it to show a few points raised in the original [issue](https://github.com/ember-redux/ember-redux/pull/101). All credit for the action creator implementation goes to him - I just wanted to speed up some of this as it's possible I may use it in the near future.
1) I added acceptance tests that exercise it from end to end
2) I show the jQuery event issue mentioned by wrapping the action creator (still not sure how I feel about this ...)
3) I learned how this feature was intended to work by reading the [docs](http://redux.js.org/docs/recipes/ReducingBoilerplate.html) and used the "async action creator" as that would be how I'd likely use it in the wild
One issue I'm fighting with right now is that since the last middleware to boot is …

[FEATURE]: unlock action creators

---

addon/components/connect.js
tests/integration/connect-test.js

This is some of the work I had bundled in #110. This makes `getAttrs` a private (static) function with a deprecation warning. I also pulled out the `changedKeys` utility function to be a bit more descriptive.

Clean up functions used in connect.

---

package.json

noticed the v6.1.0 of ember-cli-babel was out - simple upgrade here

[BUILD]: updated ember-cli-babel to 6.1.0

---

app/services/redux.js
tests/unit/services/redux-test.js

This is the one method missing from the standard redux store: http://redux.js.org/docs/api/Store.html#store-methods. Needed if added reducers dynamically to the store (e.g. changing app state structure per route or dynamically loading component reducers).

Add "replaceReducer" method to redux service.

---

addon/connect.js
tests/integration/connect-test.js

This allows reselect creators to be used, where a new instance
will be created for each instance of a connected component.
For more information on why this is useful, see: https://github.com/reactjs/reselect#sharing-selectors-with-props-across-multiple-components
This enables things like https://github.com/HeyImAlex/reselect-map to be used, which are critical for performance when mapping over large arrays in selectors (like a large list).

Support factories for stateToComputed.

---

addon/connect.js
tests/integration/connect-test.js

For developers not using inline hbs (single file components) it's often the case that you only import Ember to pass `Ember.Component` into connect. For the typescript guides I'm writing I found it was easier to default a Component type if not provided (to eliminate importing all of Ember for no real gain).

[FEATURE]: connect now provides default Ember.Component

---

index.d.ts

This isn't ready for prime time but I'm using it WIP style to build out the typescript ember-redux guides. It's mostly a copy/paste of react-redux and keeps the compiler happy for now (using the most strict settings I could crank up). Anyone more familiar have time to look this over/ help me land a solid TS type defs file for this addon?
Below is my tsconfig for the guides that I'm iterating on with 100% typescript + redux + ember
```js
{
"compilerOptions": {
"target": "es2015",
"module": "es2015",
"moduleResolution": "node",
"strictNullChecks": true,
"suppressImplicitAnyIndexErrors": true,
"allowSyntheticDefaultImports": true,
"noImplicitAny": true,
"noEmitOnError": false,
"noEmit": true,
"baseUrl": ".",
"paths": {
"welp/*": ["app/*"],
"ember-redux": …
```

[FEATURE]: add typescript type defs

---

.eslintrc.js
package.json
tests/dummy/app/reducers/items.js
tests/dummy/app/reducers/roles.js
tests/dummy/app/reducers/users.js
tests/dummy/app/sagas/counter.js
yarn.lock

I also ran `ember-modules-codemod` and added an eslint rule to error when old shims are present

[DEPENDENCY]: updated to ember-cli v2.16.2

---

docs/_layouts/examples.html

I've added a testing example to the documentation website for reference
https://github.com/toranb/redux-saga-testing-example/commit/e8a0f48ca0a48e589fe90dd2713045961c1c90e7

[WEBSITE]: added testing repository to the examples page

---

.travis.yml
package.json
testem.js
tests/acceptance/async-dispatch-test.js
tests/acceptance/rerender-test.js
tests/acceptance/route-hooks-test.js
tests/acceptance/thunk-dispatch-test.js
tests/helpers/ajax.js
tests/helpers/start-app.js
yarn.lock

https://dockyard.com/blog/2018/01/18/test-helpers-the-next-generation
The latest direction for ember/qunit seems to suggest global helpers are on the way out ;) so this just prepares for the eventual upgrade

Upgrade to ember-cli v2.18.2, bring back headless chrome, dump global helper

---

docs/_layouts/examples.html

Let's make it super easy to find the Reddit clone that is built in the intro video.
I haven't been able to verify this locally fix; how do I access this page when running locally?

Add a link to the Reddit clone that is built in the intro video

---

docs/configure.md
docs/ddau.md
docs/guides.md
docs/overview.md
docs/quickstart.md
docs/typescript.md

- Changes `var` to `const`, per modern JS convention
- Splits long lines into multiple lines for improved readability.  Prevents you from having to horizontally scroll the snippets.

Formatting improvements in documentation

---

docs/guides.md
docs/typescript.md

To modernize the docs I've updated the guides to ember v3.2 stable + the latest ember-cli. I also chose to include the new angle bracket syntax as it's the future :)
I pushed up all new guides a few minutes ago to match
https://github.com/ember-redux/guides/commits/master

DOCS: updated guides to ember v3.2 + angle bracket syntax

---

.eslintignore
.travis.yml
README.md
addon/connect.js
addon/es2019-class.js
config/ember-try.js
package.json
tests/integration/connect-test.js
yarn.lock

To workaround the latest breaking change in ember itself I've included a new class shim for ember 3.6+ to better align class support with the latest [RFC](https://github.com/emberjs/rfcs/pull/337) (using `init` instead of `constructor`)
@pzuraq -any feedback on how I'm using the compatibility helpers here? This as designed for both production/ and test code?

COMPATIBILITY: added new shim for ember 3.6 class implementation

---

package.json
testem.js
yarn.lock

For some background into the testem issue 
https://bugs.chromium.org/p/chromium/issues/detail?id=982977

DEPENDENCY: ember-cli-update to v3.11.1 and fixed testem

---

.travis.yml
addon/connect.js
addon/octane-connect.js
config/ember-try.js
package.json
tests/dummy/app/components/octane-clazz/component.js
tests/dummy/app/components/octane-clazz/template.hbs
tests/dummy/config/optional-features.json
tests/integration/octane-clazz-test.js

To support Octane added the different code path for Glimmer Component. Most of the code taken from the spike oranb/octane-interop-redux@51e8fe1. Also added the factory function supported
I didn't find any better way to differentiates between glimmer and ember component 
`component.toString() === '@ember/component' && component.reopenClass;
`
Added required test to cover happy paths

Adding support for glimmer component
