ember-redux/ember-redux

- README.md
I've been working on a yelp clone recently and decided it was a solid non trivial example that we could put up for others to checkout. Please review the twiddle as part of this pull request - I plan to tweet this out on Monday morning assuming it's not complete garbage :)
cc @cafreeman @dustinfarris @williamsbdev @brettburley
> [DOCS]: added yelp clone ember-twiddle example

- addon/components/connect.js
At this time we have a known regression that community member @dbashford found after the v1.9 release. I had him try the connect we had prior to the setProperties pull request #41 and he confirmed that before that change all was working as it did in the prior v1.8. Until we can confirm the exact root cause, I feel the project is at risk and could ultimately turn people away if they run into this same problem while we work through this regression /and patch the addon to solve whatever incompatibility we discover.
The only downside is that we will need to put other connect refactor pull requests on hold while we work closely with @dbashford to reproduce this.
> [REVERT]: undo the setProperties update (from PR #41)

- package.json
Remove the noise from other PRs that install dependencies.
> Alphabetize dependencies

- tests/acceptance/rerender-test.js
- tests/integration/runloop-test.js
@dbashford if we can merge this quick it will provide a simple way for you to verify the run.join works on your branch. I tested this w/ your fork and it was g2g
If someone lands me a LGTM+1 I'll merge and @dbashford can rebase /uncomment the test
> [TESTS]: improved runloop testing to confirm both run/and run.join work

- CHANGELOG.md
- README.md
- docs/_includes/footer.html
- package.json
Previously these badges pointed at the toranb url
> [BUILD]: updated travis and code climate badges

- package.json
- tests/dummy/app/sagas/counter.js
Simple upgrade of the redux/and redux-saga deps used for testing the addon
> [DEPENDENCY]: upgraded redux/redux-saga in the package.json

- README.md
- docs/configure.md
- docs/index.md
Working on the non code updates required for the up and coming 2X release :)
> [DOCS]: removed any mention of npm: from the docs/readme

- docs/configure.md
- docs/cookbook.md
- docs/ddau.md
- docs/index.md
- docs/quickstart.md
Preview at http://dustinfarris.com/ember-redux/
> Fix broken templates in docs

- README.md
after we merge this I don't see any reason we couldn't get 2.0 out the door :)
> [DOCS]: new ember-twiddle for 2.0

- blueprints/ember-redux/index.js
- package.json
Before optimization:
```
- dist/assets/dummy-aa8d2cb9308c6170ecb315cb96549af5.js: 34.54 KB (5.96 KB gzipped)
- dist/assets/dummy-de3c495d5da3bffcdc865aaa60f76ab3.css: 22 B (42 B gzipped)
- dist/assets/vendor-587a4740c9bd67b649fca71615bea161.js: 1 MB (244.52 KB gzipped)
- dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```
After optimization:
```
- dist/assets/dummy-aa8d2cb9308c6170ecb315cb96549af5.js: 34.54 KB (5.96 KB gzipped)
- dist/assets/dummy-de3c495d5da3bffcdc865aaa60f76ab3.css: 22 B (42 B gzipped)
- dist/assets/vendor-b7c7526584242f9ac56ad1ebdac1649a.js: 923.63 KB (233.51 KB gzipped)
- dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```
*Vendor build shrunk by ~8% (76.37 KB)*
> Optimize lodash

- .travis.yml
- package.json
We've been rocking firefox 44 and it's time for an upgrade on travis
> [BUILD]: upgrade to firefox 51

- .eslintrc.js
- .npmignore
- .travis.yml
- blueprints/.jshintrc
- bower.json
- config/ember-try.js
- config/environment.js
- ember-cli-build.js
- index.js
- package.json
- testem.js
- tests/.eslintrc.js
- tests/dummy/config/environment.js
- tests/dummy/config/targets.js
- tests/helpers/start-app.js
- tests/test-helper.js
We are a little behind so I've upgraded to ember-cli v2.13.0-beta.3 (also removed ember from the bower file)
> [DEPENDENCY]: upgraded to ember-cli v2.13.0-beta.3

- addon/components/connect.js
- tests/integration/connect-test.js
This is a stripped down version of #110, addressing only the stateToComputed issue. I'll open separate PRs for the other pieces of that PR coming soon.
> Only call stateToComputed once per state update (v2).

- addon/components/connect.js
- tests/integration/connect-test.js
> Add a more descriptive error message on redux prop set.

- tests/acceptance/route-hooks-test.js
- tests/dummy/app/components/query-params-list/component.js
- tests/dummy/app/items/route.js
- tests/dummy/app/query-params/route.js
- tests/dummy/app/query-params/template.hbs
- tests/dummy/app/reducers/index.js
- tests/dummy/app/reducers/query-params.js
- tests/dummy/app/router.js
- tests/dummy/app/templates/application.hbs
This is the bulk of @sandersky 's great work in a older PR he wrote. I think it's a great example I can point people at and because it was so well thought out I decided to include it in the project :)
> [TESTS]: added queryParams + connect example

- addon/middleware/index.js
- addon/reducers/index.js
- addon/services/redux.js
- app/enhancers/index.js
- app/reducers/index.js
- app/reducers/optional.js
- app/services/redux.js
- docs/configure.md
- yarn.lock
As part of the feedback for PR #120 @foxnewsnetwork passed over a createStore that is more extensible (while not breaking the app itself). I took inspiration from that and my previous PR to build this one #feedbackWelcome
> A more robust createStore inspired by @foxnewsnetwork

- package.json
- testem.js
- tests/helpers/module-for-acceptance.js
- yarn.lock
Simple upgrade to the very latest stable ember/ember-cli
> [DEPENDENCY]: updated to ember & ember-cli v2.16

- docs/_layouts/default.html
- docs/assets/default.css
Added:
> In this video, learn how to build a reddit clone with ember-redux, redux-thunk, and reselect.
I thought it was useful to mention Redux  thunk and reselect because there are so many possible ingredients that can go into a redux stack.
I tried to make the styling non-horrible; happy to adjust wording or styling if you have better ideas.
> Add a description and link to the source for the intro video

- README.md
- docs/_layouts/docs.html
- docs/community.md
Quick and dirty! 
Feel free to tell critique.
> Adding verbiage for slack and how to edit docs. 

- .travis.yml
- addon/es2015-class.js
- config/ember-try.js
- package.json
- yarn.lock
Robert Jackson gave me a path forward on this ember 3.1 ES5GETTER regression
https://github.com/emberjs/ember.js/issues/16519#issuecomment-381400821
> es2015Class: WrappedComponent prototype injection now plays nice w/ ember 3.1

- tests/integration/connect-test.js
- tests/unit/services/redux-test.js
We had a unit test for this feature previously but as I went back to see how that worked I found myself writing a full integration test to better understand what this looked like 4 real
> TESTS: add component integration test for replaceReducer

- .travis.yml
- config/ember-try.js
- package.json
- tests/dummy/app/components/fetch-users/component.js
- tests/helpers/ajax.js
- tests/integration/runloop-test.js
Nothing special ;) just making a bump to ember latest (stable)
> Upgrade to ember v3.2

- .eslintignore
- .eslintrc.js
- .gitignore
- .npmignore
- .travis.yml
- config/ember-try.js
- package.json
- testem.js
- yarn.lock
Just a quick update to ember-cli v3.3.0/ember v3.3.0
> DEPENDENCY: updated ember/ember-cli to v3.3.0

- README.md
A few minor tweaks to the readme
> README: update from var -> const

- .travis.yml
- config/ember-try.js
- package.json
- yarn.lock
Just keeping up w/ the ember ecosystem ya'll
> DEPENDENCY: update to ember/ember-cli v3.4

- .travis.yml
- config/ember-try.js
- yarn.lock
Fix the NPM security audit warning
> SECURITY: updated merge to v1.2.1

- .travis.yml
- config/ember-try.js
- package.json
- tests/dummy/app/utilities/ajax.js
- tests/helpers/ajax.js
- yarn.lock
> DEPENDENCY: upgrade to ember source 3.9

- index.d.ts
> [#187] Fix declaration file for newer versions of typescript

- yarn.lock
Upgrade a ton of dev dependencies w/ `yarn upgrade`
> DEPENDENCY: yarn upgrade

- package.json
- yarn.lock
> DEPENDENCY: upgrade to ember source 3.11

- .travis.yml
- tests/acceptance/octane-class-test.js
- tests/dummy/app/components/octane-actioncreator/component.js
- tests/dummy/app/components/octane-actioncreator/template.hbs
- tests/dummy/app/components/octane-factory/component.js
- tests/dummy/app/components/octane-factory/template.hbs
- tests/dummy/app/octane-actionz/template.hbs
- tests/dummy/app/octane-factorie/template.hbs
- tests/dummy/app/router.js
The 2 biggie features we didn't yet have tests for to confirm glimmer support are action creators & [factory functions](https://github.com/glimmer-redux/glimmer-redux/issues/3). Including these so we can continue to make changes and improve the library with confidence :)
> TESTS: added tests for glimmer components to exercise action creator & factory functions

- .travis.yml
- config/ember-try.js
- package.json
- tests/acceptance/rerender-test.js
- yarn.lock
> DEPENDENCY: upgrade to ember source v3.17

- yarn.lock
> DEPENDENCY: yarn upgrade for security

- .travis.yml
- config/ember-try.js
- package.json
- yarn.lock
Keeping up w/ the stable ember release train :)
> DEPENDENCY: upgrade to ember source v3.19

- yarn.lock
> DEPENDENCY: another yarn upgrade for security

- package.json
- yarn.lock
Just updating dependencies and ember source
> DEPENDENCY: bump to ember source 3.20.2

- .travis.yml
- config/ember-try.js
- package.json
- yarn.lock
keeping up w/ the ember release cycle
> DEPENDENCY: upgrade to ember 3.22

- .travis.yml
- config/ember-try.js
- package.json
- yarn.lock
> DEPENDENCY: upgrade to ember 3.24

- .travis.yml
- config/ember-try.js
- package.json
- yarn.lock
> DEPENDENCY: upgrade to ember 3.26
